version: '3'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.2-community
    ports:
      - "9000:9000"
    volumes:
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_logs:/opt/sonarqube/logs
    - sonarqube_temp:/opt/sonarqube/temp
  jenkins:
    container_name: jenkinsblueocean
    image: jenkinsci/blueocean
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
